const base = process.env.BEACON_API_URL || "http://127.0.0.1:8000/api/v1";
let authority;
const check = (condition, message) => { if (!condition) throw new Error(message); };
const json = async (path, init = {}) => {
  const response = await fetch(`${base}${path}`, init);
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(`${init.method || "GET"} ${path}: ${response.status} ${body.detail || "failed"}`);
  return body;
};
const status = async (path, init = {}) => (await fetch(`${base}${path}`, init)).status;

const health = await json("/health");
check(health.database === "postgresql/postgis" && health.redis === "PONG", "Infrastructure health failed");
const languageResponse = await json("/languages");
const languages = languageResponse.languages;
check(languages.length >= 12 && languages.some((item) => item.code === "hne") && languages.some((item) => item.code === "ta"), "Indian language catalog is incomplete");
const identityTranslation = await json("/translate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: "Safety update", source_language: "en", target_language: "en" }) });
check(identityTranslation.text === "Safety update" && identityTranslation.available === true, "Safe same-language translation failed");
const login = await json("/authority/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: "admin@beacon.local", password: "BeaconDemo!26" }) });
check(login.token.startsWith("ses_"), "Authority login did not issue an opaque session");
authority = { Authorization: `Bearer ${login.token}`, "Content-Type": "application/json" };
await json("/demo/reset", { method: "POST", headers: authority, body: "{}" });

const events = [];
const ws = new WebSocket(base.replace(/^http/, "ws") + `/ws?token=${encodeURIComponent(login.token)}`);
ws.onmessage = (message) => events.push(JSON.parse(message.data));
await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; setTimeout(() => reject(new Error("WebSocket timeout")), 4_000); });
const anonymous = new WebSocket(base.replace(/^http/, "ws") + "/ws");
const anonymousClose = await new Promise((resolve, reject) => { anonymous.onclose = (event) => resolve(event.code); anonymous.onerror = () => {}; setTimeout(() => reject(new Error("Anonymous WebSocket was not rejected")), 4_000); });
check(anonymousClose === 1008, "Anonymous WebSocket did not close with policy violation");

const session = await json("/citizens/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Smoke Test Citizen", phone: "9000000001", language: "en", device_id: "smoke-device" }) });
const otherSession = await json("/citizens/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Other Citizen", phone: "9000000002", language: "en", device_id: "other-device" }) });
check(session.token.startsWith("cses_"), "Citizen registration did not issue an opaque session");
const citizenAuth = { Authorization: `Bearer ${session.token}` };
const citizenEvents = [], otherEvents = [];
const citizenWs = new WebSocket(base.replace(/^http/, "ws") + `/ws?token=${encodeURIComponent(session.token)}`);
const otherWs = new WebSocket(base.replace(/^http/, "ws") + `/ws?token=${encodeURIComponent(otherSession.token)}`);
citizenWs.onmessage = (message) => citizenEvents.push(JSON.parse(message.data)); otherWs.onmessage = (message) => otherEvents.push(JSON.parse(message.data));
await Promise.all([citizenWs, otherWs].map((socket) => new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; setTimeout(() => reject(new Error("Citizen WebSocket timeout")), 4_000); })));
const form = new FormData();
Object.entries({ citizen_id: session.citizen.id, hazard_type: "flood", severity: "high", text: "Flood water rising near the road, one person injured", requested_help: "Safe route and assessment", latitude: "21.2514", longitude: "81.6296" }).forEach(([key, value]) => form.set(key, value));
const validPng = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");
form.set("media", new Blob([validPng], { type: "image/png" }), "evidence.png");
const report = await json("/reports", { method: "POST", headers: citizenAuth, body: form });
check(report.analysis.analysis_available && report.analysis.specialist_outputs?.verifier, "AI specialist result missing");
check(report.analysis.verification?.human_review_required === true, "External verification advisory or human-review guardrail missing");
check((report.analysis.verification?.sources || []).every((source) => /^https?:\/\//.test(source.url)), "Verification returned a non-clickable or unsafe source URL");
check(report.media[0]?.provider === "local" || report.media[0]?.provider === "cloudinary", "Media was not retained");
const refreshedVerification = await json(`/incidents/${report.incident.id}/source-check`, { method: "POST", headers: authority, body: "{}" });
check(refreshedVerification.human_review_required === true && typeof refreshedVerification.summary === "string", "Authority source refresh failed");
const duplicateForm = new FormData();
Object.entries({ citizen_id: session.citizen.id, hazard_type: "flood", severity: "high", text: "Flood water rising near the road, one person injured", latitude: "21.2515", longitude: "81.6297" }).forEach(([key, value]) => duplicateForm.set(key, value));
const duplicate = await json("/reports", { method: "POST", headers: citizenAuth, body: duplicateForm });
check(duplicate.incident.id === report.incident.id && duplicate.incident.trust_state === "Corroborated", "Duplicate report was not clustered/corroborated");
const invalidMedia = new FormData();
Object.entries({ citizen_id: session.citizen.id, hazard_type: "flood", severity: "low", text: "Unsupported attachment test", latitude: "21.2515", longitude: "81.6297" }).forEach(([key, value]) => invalidMedia.set(key, value));
invalidMedia.set("media", new Blob(["unsafe"], { type: "text/plain" }), "unsafe.txt");
check(await status("/reports", { method: "POST", headers: citizenAuth, body: invalidMedia }) === 415, "Unsupported upload was not rejected");
const unauthForm = new FormData();
Object.entries({ citizen_id: session.citizen.id, hazard_type: "flood", severity: "low", text: "Unauthenticated report attempt", latitude: "21.2515", longitude: "81.6297" }).forEach(([key, value]) => unauthForm.set(key, value));
check(await status("/reports", { method: "POST", body: unauthForm }) === 401, "Unauthenticated citizen report was accepted");
check(await status(`/incidents/${report.incident.id}/bypass`, { method: "POST", headers: { Authorization: "Bearer official_responder", "Content-Type": "application/json" }, body: JSON.stringify({ confirmed: true, reason: "Must not be authorized" }) }) === 403, "Responder bypass authorization failed");

const incident = await json(`/incidents/${report.incident.id}/bypass`, { method: "POST", headers: authority, body: JSON.stringify({ confirmed: true, reason: "Smoke test emergency publication path" }) });
check(incident.trust_state === "Verified", "Bypass did not verify incident");
const alert = await json("/alerts", { method: "POST", headers: authority, body: JSON.stringify({ incident_id: incident.id, title: "Smoke test advisory", body: "Avoid the affected test area.", severity: "high" }) });
const context = await json("/context?lat=21.2514&lon=81.6296");
check(context.verified_incidents.some((item) => item.id === incident.id), "Verified map layer missing incident");
check(context.alerts.some((item) => item.id === alert.id && Number.isFinite(item.latitude)), "Official alert location missing");

const sos = await json("/sos", { method: "POST", headers: { ...citizenAuth, "Content-Type": "application/json" }, body: JSON.stringify({ citizen_id: session.citizen.id, latitude: 21.2514, longitude: 81.6296, note: "Smoke test SOS" }) });
const recovered = await json("/sos/active", { headers: citizenAuth });
check(recovered.sos?.id === sos.id && recovered.assignment === null, "Active SOS recovery failed before assignment");
const assignment = await json("/assignments", { method: "POST", headers: authority, body: JSON.stringify({ sos_id: sos.id, responder_id: "official_responder", eta_minutes: 6, note: "Smoke test dispatch" }) });
await json(`/assignments/${assignment.id}/En%20route`, { method: "PATCH", headers: authority, body: "{}" });
const recoveredAssigned = await json("/sos/active", { headers: citizenAuth });
check(recoveredAssigned.assignment?.id === assignment.id, "Active SOS recovery did not include assignment");
const cancellableSos = await json("/sos", { method: "POST", headers: { ...citizenAuth, "Content-Type": "application/json" }, body: JSON.stringify({ citizen_id: session.citizen.id, latitude: 21.2514, longitude: 81.6296, note: "Cancellation smoke test" }) });
const cancelled = await json(`/sos/${cancellableSos.id}/cancel`, { method: "POST", headers: citizenAuth });
check(cancelled.status === "Cancelled", "SOS cancellation failed");

const community = await json("/communities", { method: "POST", headers: authority, body: JSON.stringify({ name: "Smoke test support group", incident_id: incident.id, approved: true }) });
const message = await json(`/communities/${community.id}/messages`, { method: "POST", headers: authority, body: JSON.stringify({ sender_role: "admin", sender_name: "ignored", body: "Official smoke test message" }) });
const citizenMessage = await json(`/communities/${community.id}/messages`, { method: "POST", headers: { ...citizenAuth, "Content-Type": "application/json" }, body: JSON.stringify({ sender_role: "admin", sender_name: "Spoofed Admin", body: "Citizen identity smoke test" }) });
check(citizenMessage.sender_role === "citizen" && citizenMessage.sender_name === session.citizen.name && citizenMessage.official === false, "Community sender identity could be spoofed");
check(await status(`/communities/${community.id}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: "Anonymous" }) }) === 401, "Anonymous community message was accepted");
await json(`/communities/${community.id}/messages/${message.id}/moderate`, { method: "PATCH", headers: authority, body: JSON.stringify({ status: "flagged", reason: "Smoke test moderation" }) });
const outdated = await json(`/incidents/${incident.id}/decision`, { method: "POST", headers: authority, body: JSON.stringify({ action: "outdated", reason: "Smoke test conditions changed" }) });
check(outdated.trust_state === "Outdated" && outdated.invalidated_alerts === 1, "Incident decision did not atomically invalidate its alert");

await new Promise((resolve) => setTimeout(resolve, 350));
check(events.some((event) => event.event === "incident.created"), "Realtime incident event missing");
check(events.some((event) => event.event === "dispatch.updated"), "Realtime dispatch event missing");
check(events.some((event) => event.event === "alert.corrected"), "Realtime correction event missing");
check(citizenEvents.some((event) => event.event === "sos.created" && event.payload.id === sos.id), "Owner did not receive scoped SOS event");
check(citizenEvents.some((event) => event.event === "dispatch.updated" && event.payload.sos_id === sos.id), "Owner did not receive scoped dispatch event");
check(!otherEvents.some((event) => ["sos.created", "sos.location", "dispatch.updated"].includes(event.event)), "Other citizen received private SOS/dispatch data");
check(citizenEvents.some((event) => event.event === "alert.published") && otherEvents.some((event) => event.event === "alert.published"), "Authenticated alert broadcast did not reach citizens");
const audit = await json("/audit", { headers: authority });
check(audit.some((entry) => entry.action === "verification_bypassed"), "Immutable bypass audit missing");
check(audit.some((entry) => entry.action === "message_flagged"), "Moderation audit missing");
check(audit.some((entry) => entry.action === "alert_auto_corrected"), "Automatic alert correction audit missing");
check(audit.some((entry) => entry.action === "external_source_check_refreshed"), "External source-check audit missing");
const queue = await json("/authority/queue", { headers: authority });
check(queue.delivery.some((entry) => entry.channel === "sms/msg91" && entry.status === "not_configured"), "Delivery fallback ledger missing SMS result");

ws.close(); citizenWs.close(); otherWs.close();
await json("/demo/reset", { method: "POST", headers: authority, body: "{}" });
console.log(JSON.stringify({ ok: true, postgis: health.postgis, redis: health.redis, ai_provider: report.analysis_meta.provider, media_provider: report.media[0].provider, media_fallback_reason: report.media[0].fallback_reason || null, realtime_events: events.length }));
